language: python
sudo: required

services:
  - docker

script:
  - docker build -t linkedinscraper:$(git describe --abbrev=0 --tags) .
  - docker images

deploy:
  skip_cleanup: true
  provider: script
  script: bash docker_push.sh
  on:
    tags: true